### ISSUE TITLE
IRC to in game chat

### ISSUE THREAD

**Issue by skinofstars** [minecuna/server#3]
Not sure if this is possible in Realms, but certainly on hosted servers you can hook up in game chat with an IRC channel. 

We used to do it on the WO server... though that may have been XMPP, but same result.

**Comment by meshy** [comment]
Would it be 2-way, or is it just that the conversation is copied into irc?

We used to have a teamspeak server...whatever happened to that?

**Comment by skinofstars** [comment]
Yeah, there is NoLogo's mumble server, but people seem to congragate around IRC. You can certainly do 2-way with JOIN/PART messages, etc, on hosted servers + bukkit. As I said though, I don't know if this is possible with Realms. 

I'd like it though as I kinda think of minecuna as a social space as well.

**Comment by ghickman** [comment]
Yes, I'd love this! I looked into this back when we were using Crafty and AFAICT it's only possible with Bukkit which has traditionally been 1-2 major versions behind and is now dead. So definitely not possible with Realms unfortunately.

> I'd like it though as I kinda think of minecuna as a social space as well.

Yes, it's always been that for the rest of us. Community first, game second =)

**Comment by meshy** [comment]
If it's two way, them I'm 100% behind it ... if it's still possible `:/`

**Comment by ghickman** [comment]
Yes, just to be explicit I would be completely up for this if it's possible and two-way.

I'm going to close this issue since I don't think there exists a way to do this [right now]. Please feel free to re-open should anyone find a way of doing it!

**Comment by skinofstars** [comment]
Ok, it's a nice idea, but ain't gonna happen till they do the 1.8+ API. Closing.
